name: Test

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup V
      uses: prantlf/setup-v-action@v1
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Test
      run: |
        v test .
        v run src/help_test.v
        v test src/version_test.v
